/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2019-01-02

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdio.h>
#include "stm32f10x.h"
#include "lcd.h"
#include "delay.h"

/* Private typedef */
typedef enum {PULL_UP, PULL_DOWN, NO_PULL} pull_Up_Down_State_t;
typedef enum {PUSH_PULL_OUT, OPEN_DRAIN_OUT, ALTERNATE_PUSH_PULL_OUT, ALTERNATE_OPEN_DRAIN_OUT} out_State_t;
typedef enum {SPEED_2_MHZ, SPEED_10_MHZ, SPEED_50_MHZ} out_Speed_State_t;
typedef enum {ANALOG_IN, FLOATING_IN, PULLED_IN} in_State_t;
/* Private define  */
/* Private macro */
/* Private variables */

/* Private function prototypes */
 void LCD_config_pins(void);
 void setPinAsOut(GPIO_TypeDef *port, uint8_t pin, out_State_t outState, out_Speed_State_t speed);
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	char lcd_buffer[20];
	unsigned int var = RCC->CFGR;

	LCD_config_pins();
	lcd_init();
	lcd_send_string("STM32F100C8T6 demo");
	//lcd_goto_xy(0,1);

	/* TODO - Add your application code here */

	/* Infinite loop */
	while (1)
	{
		GPIOB->ODR ^= (1 << 12);
		delay_ms(1000);
	}
}

void LCD_config_pins(void)
{

	// Enable Clock for GPIO
	RCC->APB2ENR |= ((1 << 3) | (1 << 2)); // Enable clock for GPIOA and GPIOB

	// set LCD pins as push-pull outputs @ 10 MHz
	setPinAsOut(LCD_RS_PORT, LCD_RS_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_RW_PORT, LCD_RW_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_EN_PORT, LCD_EN_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(GPIOB, 12, PUSH_PULL_OUT, SPEED_10_MHZ);

	setPinAsOut(LCD_D4_PORT, LCD_D4_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_D5_PORT, LCD_D5_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_D6_PORT, LCD_D6_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_D7_PORT, LCD_D7_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
}

void setPinAsOut(GPIO_TypeDef *port, uint8_t pin, out_State_t outState, out_Speed_State_t speed)
{
	if(pin <= 7)
	{
		pin *= 4;
		switch(speed)
		{
		case SPEED_2_MHZ:
			port->CRL &= ~(1 << pin);
			pin++;
			port->CRL |= (1 << pin);
			break;
		case SPEED_10_MHZ:
			port->CRL |= (1 << pin);
			pin++;
			port->CRL &= ~(1 << pin);
			break;
		case SPEED_50_MHZ:
			port->CRL |= (1 << pin);
			pin++;
			port->CRL |= (1 << pin);
			break;
		default: // SPEED_10_MHZ
			port->CRL |= (1 << pin);
			pin++;
			port->CRL &= ~(1 << pin);
			break;
		}

		pin++;

		switch(outState)
		{
		case PUSH_PULL_OUT:
			port->CRL &= ~(1 << pin);
			pin++;
			port->CRL &= ~(1 << pin);
			break;
		case OPEN_DRAIN_OUT:
			port->CRL |= (1 << pin);
			pin++;
			port->CRL &= ~(1 << pin);
			break;
		case ALTERNATE_PUSH_PULL_OUT:
			port->CRL &= ~(1 << pin);
			pin++;
			port->CRL |= (1 << pin);
			break;
		case ALTERNATE_OPEN_DRAIN_OUT:
			port->CRL |= (1 << pin);
			pin++;
			port->CRL |= (1 << pin);
			break;
		default: // PUSH_PULL_OUT
			port->CRL &= ~(1 << pin);
			pin++;
			port->CRL &= ~(1 << pin);
			break;
		}
	}

	else
	{
		pin -= 8;
		pin *= 4;
		switch(speed)
		{
		case SPEED_2_MHZ:
			port->CRH &= ~(1 << pin);
			pin++;
			port->CRH |= (1 << pin);
			break;
		case SPEED_10_MHZ:
			port->CRH |= (1 << pin);
			pin++;
			port->CRH &= ~(1 << pin);
			break;
		case SPEED_50_MHZ:
			port->CRH |= (1 << pin);
			pin++;
			port->CRH |= (1 << pin);
			break;
		default: // SPEED_10_MHZ
			port->CRH |= (1 << pin);
			pin++;
			port->CRH &= ~(1 << pin);
			break;
		}

		pin++;

		switch(outState)
		{
		case PUSH_PULL_OUT:
			port->CRH &= ~(1 << pin);
			pin++;
			port->CRH &= ~(1 << pin);
			break;
		case OPEN_DRAIN_OUT:
			port->CRH |= (1 << pin);
			pin++;
			port->CRH &= ~(1 << pin);
			break;
		case ALTERNATE_PUSH_PULL_OUT:
			port->CRH &= ~(1 << pin);
			pin++;
			port->CRH |= (1 << pin);
			break;
		case ALTERNATE_OPEN_DRAIN_OUT:
			port->CRH |= (1 << pin);
			pin++;
			port->CRH |= (1 << pin);
			break;
		default: // PUSH_PULL_OUT
			port->CRH &= ~(1 << pin);
			pin++;
			port->CRH &= ~(1 << pin);
			break;
		}
	}

}
