/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2019-01-02

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdio.h>
#include "stm32f10x.h"
#include "lcd.h"
#include "delay.h"
#include "gpio.h"

/* Private typedef */
/* Private define  */
#define LED_PORT	GPIOB
#define LED_PIN		12

/* Private macro */
/* Private variables */
volatile int PB15_IRQCounter = 0, PB14_IRQCounter = 0;

/* Private function prototypes */
void LCD_config_pins(void);

/* Private functions */
void EXTI15_10_IRQHandler(void)
{
	if(EXTI->PR & EXTI_PR_PR15)
	{
		PB15_IRQCounter++;
		LED_PORT->ODR |= (1 << LED_PIN);
		EXTI->PR |= EXTI_PR_PR15; // reset the request flag
	}

	if(EXTI->PR & EXTI_PR_PR14)
	{
		PB14_IRQCounter++;
		LED_PORT->ODR &= ~(1 << LED_PIN);
		EXTI->PR |= EXTI_PR_PR14; // reset the request flag
	}
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	char lcd_buffer[20];

	LCD_config_pins();

	setPinAsOut(GPIOB, 12, PUSH_PULL_OUT, SPEED_10_MHZ);

	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

	AFIO->EXTICR[3] |= AFIO_EXTICR4_EXTI14_PB;
	AFIO->EXTICR[3] |= AFIO_EXTICR4_EXTI15_PB;

	EXTI->IMR |= EXTI_IMR_MR14;
	EXTI->FTSR |= EXTI_FTSR_TR14;

	EXTI->IMR |= EXTI_IMR_MR15;
	EXTI->FTSR |= EXTI_FTSR_TR15;

	NVIC_EnableIRQ(EXTI15_10_IRQn);
	NVIC_SetPriority(EXTI15_10_IRQn, 0);

	lcd_init();
	/* TODO - Add your application code here */

	/* Infinite loop */
	while (1)
	{
		lcd_goto_xy(0,0);
		sprintf(lcd_buffer, "EXTI_PB15: %d", PB15_IRQCounter);
		lcd_send_string(lcd_buffer);

		lcd_goto_xy(0,1);
		sprintf(lcd_buffer, "EXTI_PB14: %d", PB14_IRQCounter);
		lcd_send_string(lcd_buffer);
	}
}

void LCD_config_pins(void)
{

	// Enable Clock for GPIO
	RCC->APB2ENR |= ((1 << 3) | (1 << 2)); // Enable clock for GPIOA and GPIOB

	// set LCD pins as push-pull outputs @ 10 MHz
	setPinAsOut(LCD_RS_PORT, LCD_RS_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_RW_PORT, LCD_RW_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_EN_PORT, LCD_EN_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);

	setPinAsOut(LCD_D4_PORT, LCD_D4_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_D5_PORT, LCD_D5_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_D6_PORT, LCD_D6_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
	setPinAsOut(LCD_D7_PORT, LCD_D7_PIN, PUSH_PULL_OUT, SPEED_10_MHZ);
}
